// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZINBvoFZ4wRrH029wCIjSFXjTSG3lsUs',
    appId: '1:1095191791093:web:49677ca2c00c11c48c4cbc',
    messagingSenderId: '1095191791093',
    projectId: 'movie-app-1122',
    authDomain: 'movie-app-1122.firebaseapp.com',
    storageBucket: 'movie-app-1122.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPap0HP7FQTrNY9CBG21ajn3oNRI0JD9U',
    appId: '1:1095191791093:android:ee06f86637d8c60c8c4cbc',
    messagingSenderId: '1095191791093',
    projectId: 'movie-app-1122',
    storageBucket: 'movie-app-1122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD947YBdAyT9_STpIb7j1fxtBHBNkmi0LM',
    appId: '1:1095191791093:ios:a1225b861cfb44628c4cbc',
    messagingSenderId: '1095191791093',
    projectId: 'movie-app-1122',
    storageBucket: 'movie-app-1122.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD947YBdAyT9_STpIb7j1fxtBHBNkmi0LM',
    appId: '1:1095191791093:ios:a1225b861cfb44628c4cbc',
    messagingSenderId: '1095191791093',
    projectId: 'movie-app-1122',
    storageBucket: 'movie-app-1122.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZINBvoFZ4wRrH029wCIjSFXjTSG3lsUs',
    appId: '1:1095191791093:web:8d3e2130e1402b168c4cbc',
    messagingSenderId: '1095191791093',
    projectId: 'movie-app-1122',
    authDomain: 'movie-app-1122.firebaseapp.com',
    storageBucket: 'movie-app-1122.firebasestorage.app',
  );
}
